name: VoteSystem
version: ${project.version}
main: de.hakuyamu.skybee.votesystem.VoteSystem
api-version: 1.18
depend: [ Votifier, Vault ]
authors: [ Hakuyamu ]

commands:
  vote:
    description: vote command
  voteadmin:
    permission: skybee.votesystem.command.admin
    aliases: [ vadmin ]
  vcshop:
    aliases: [ votecoinshop, pshop ]
  vc:
    aliases: [ votecoins, pollen ]