name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Maven Cache
      uses: skjolber/maven-cache-github-action@v1.1
      with:
        step: restore
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven Cache
      uses: skjolber/maven-cache-github-action@v1.1
      with:
        step: save
